keylime/keylime-vagrant-ansible-tpm-emulator

- README.md
- roles/ansible-keylime-tpm12/tasks/git-repos.yml
- roles/ansible-keylime-tpm12/tasks/keylime.yml
- roles/ansible-keylime-tpm12/tasks/main.yml
- roles/ansible-keylime-tpm20/tasks/git-repos.yml
- roles/ansible-keylime-tpm20/tasks/keylime.yml
- roles/ansible-keylime-tpm20/tasks/main.yml
Inline with the agreed repo name change from python-keylime
to keylime, this PR makes the needed changes.
> Rename former repository references

- roles/ansible-keylime-tpm12/tasks/keylime.yml
- roles/ansible-keylime-tpm20/tasks/keylime.yml
Require EK should be false (as its a software TPM)
Also set ca provider as openssl, which works without golang
configuration (which we can add later)
> Set require_ek to false and ca provider to openssl

- Vagrantfile
- roles/ansible-keylime-tpm20/tasks/packages.yml
Allow user to spin up a variable number of VMs named keylime1,keylime2...keylimeN. The VMs use ansible to setup and download keylime. They can also use a shared folder to reference the keylime codebase, and provide and easier development loop. It fixes some virtual-box resource allocation errors from the original code, and an issue where ansible attempted to use python2 rather than python3. 
Set the for loop to 1 to have same behavior as original, make sure to fill in your desired shared folder, and make sure to set the --provider flag to either libvert or virtualbox.  A private network is also connected to allow keylime instances to communicate between each other, ip = 10.0.0."KEYLIME#"1
> Multi VM setup

- README.md
New args can now be passed to the vagrant command and allow
injection of options such as the amount of instances, cpu and
memory.
This change outlines the new args within the README.md file
> Add details on new args available for Vagrant

- roles/ansible-keylime-tpm20/tasks/packages.yml
The current impelementation of the keylime_verifier requires zmq. Ensure
that it is installed during provisioning.
> roles:tpm20:packages: add required py3-zmq dep

- Vagrantfile
Users will experience a failure unless a private network is pre
set before running vagrant.
Let's comment it out and hvae uses configure it themselves (should
they wish to).
> Comment out private network and prompt to config

- roles/ansible-keylime-tpm20/tasks/ibm-tpm.yml
Fedora packaging added the following to the systemd file for
tpm2-abrmd:
`ConditionPathExistsGlob=/dev/tpm*`
This causes the emulator to fail.
This change uses a linereplace to comment out the aforementioned.
> Comment out ConditionPathExistsGlob

- Vagrantfile
- roles/ansible-keylime-tpm20/tasks/ibm-tpm.yml
This updates the Vagrant Ansible role to:
- Add a verbose option to Ansible for debugging purposes.
- Update the IBM TPM task to specify the new software TPM `scripts` directory after the directory moved.
- Fix formatting issues in Vagrantfile.
> Updates to Vagrant Ansible role

- .gitignore
- README.md
- Vagrantfile
- vagrant_variables.yml.sample
This allows the user to specify defaults in a vagrant variables config file without having to specify options on the command line for each vagrant command. I opted to not commit the actual `vagrant_variables.yml` file so that the user is forced to explicitly set and use the config file to avoid any confusion.
> Add vagrant config file for setting defaults

- roles/ansible-keylime-tpm12/tasks/packages.yml
- roles/ansible-keylime-tpm20/tasks/packages.yml
Bringing everything into a single ansible dnf module calls allows
ansible to make a single call to the dnf binary with all of the packages
as arguments.
This shaves about 2 minutes off of provisioning a new machine in my
testing.
> Speed up ansible package installs

- Vagrantfile
- extras/.vimrc
- playbook.yml
- quality_of_life.yml
This patch adds a `--qualityoflife` option to the Vagrantfile, which will make life a bit easier in the VMs started by Vagrant by giving you a few nice-to-haves, such as Powerline for an improved command line prompt and 'll' as an alias to 'ls -lAh's.
Opinions and reviews welcome!
> Add a  "quality of life" option to Vagrantfile

- playbook.yml
The role made its way into the file by mistake, as part of testing something else.
Removing it.
Signed-off-by: axelsimon <github@axelsimon.net>
> Remove "ansible-keylime-user" role

- README.md
Remove obsolete section on configuring TPM 1.2 or 2.0 (it's all 2.0 now).
Add instructions on how to update Keylime in a VM + upgrading the VM.
> Add instructions for VM upgrade, remove software TPM config

- README.md
- Vagrantfile
- roles/ansible-keylime-tpm20/tasks/git-repos.yml
- roles/ansible-keylime-tpm20/tasks/ibm-tpm.yml
- roles/ansible-keylime-tpm20/tasks/packages.yml
Align on installer.sh:
- update packages task
- stop using abrmd
Note: creates a working Keylime VM, but exporting the following
environment variable is still needed to start keylime_agent:
export TPM2TOOLS_TCTI="mssim:port=2321"
> Update to Fedora 35

- Vagrantfile
This is needed for certain versions of VirtualBox if you
are using that as the Vagrant provider. Otherwise you can
get a weird error like:
Stderr: VBoxManage: error: Failed to construct device 'ichac97' instance #0 (VERR_CFGM_NOT_ENOUGH_SPACE)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
Signed-off-by: Michael Peters <mpeters@redhat.com>
> Remove audio from VM

- roles/ansible-keylime-tpm20/tasks/keylime.yml
New since Keylime 6.5.0. Old config files won't work, so this should fix breakage with up-to-date Keylime clones.
Signed-off-by: Mark Bestavros <mbestavr@redhat.com>
> Add support for Keylime's new config format

- docs/vagrant-setup-guide-fedora.md
While this should hopefully be only a temporary workaround, it should be publicly accessible.
> Document a workaround for broken ima_emulator.service

- Vagrantfile
This should hopefully be a permanent fix for `ima_emulator.service` breaking on VM startup.
Signed-off-by: Mark Bestavros <mbestavr@redhat.com>
> Fix ima_emulator.service not starting correctly by running tpm2_startup -c

- docs/vagrant-setup-guide-fedora.md
The instructions were out of date, and I noticed when standing my multi-VM setup back up after https://github.com/keylime/keylime-vagrant-ansible-tpm-emulator/pull/67. Also made some other miscellaneous fixes to that section.
Signed-off-by: Mark Bestavros <mbestavr@redhat.com>
> Update multi-VM docs for new config format + misc fixes

- roles/ansible-keylime-tpm20/tasks/keylime.yml
As it turns out, the fix for supporting new-format config files in #65 happened too early in `keylime.yml`. It converted config files to the new format before certain values (like disabling `ekcert` checking for development) happened. This fixes that.
Signed-off-by: Mark Bestavros <mbestavr@redhat.com>
> Fix keylime.conf changes not being reflected in new config files

- README.md
I assume this was an old name for keylime_tenant, but regardless it should be changed.
Fixes issue #42
> Fix doc use of unknown keylime_node command

- roles/tpm_setup/files/ima_emulator.service
- roles/tpm_setup/files/tpm_emulator.service
- roles/tpm_setup/tasks/main.yml
This uses the tpm_vtpm_proxy kernel module to expose the swtpm as /dev/tpm0 so it appears more like a real tpm device.
Makes it easier to use the rust agent as well.
> Use swtpm in chardev mode

- docs/vagrant-setup-guide-fedora.md
- Specify that the SHA256 PCR-10 value (instead of SHA1 PCR-10) should be filled
- Update command to create an allow list
> Update setup guide for Fedora
